# etape 1: build
FROM python:3.11-slim AS builder

WORKDIR /app

COPY /requirements.txt /app/

RUN pip3 install  --break-system-packages --no-cache-dir -r requirements.txt

COPY . .

# etape 2: production
FROM python:3.11-slim
COPY --from=builder /app /app
WORKDIR /app

EXPOSE 8000

ENTRYPOINT ["python3", "manage.py"]

CMD ["runserver", "0.0.0.0:8000"]
